### ISSUE TITLE
error while loading shared libraries: libmbedcrypto.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by simonbowen** [valiot/opex62541#10]
I am keen on using Elixir for connecting to an OPCUA service however I am getting this issue.

```
home/simonbowen/opcua/_build/dev/lib/opex62541/priv/opc_ua_client: error while loading shared libraries: libmbedcrypto.so.1: cannot open shared object file: No such file or directory`
```

I am running Ubuntu 20.20.

I know that this package hasn't been tested against this version of Ubuntu, but could someone point me in the right direction for resolving this issue? I am guessing I might need to set a flag somewhere before compiling?

**Comment by alde103** [comment]
Hi @simonbowen,

The `libmbedcrypto` library is part of the `mbedtls` (libmbedtls-dev) package (I have 2.8.0 version), make sure you have installed all the opex62541 dependencies.
```bash
sudo apt-get install git build-essential gcc pkg-config cmake python libmbedtls-dev
```
to check that the package is installed correctly you can use the following: 
```bash
whereis libmbedcrypto
```
In my particular case it is located in `/usr/lib/x86_64-linux-gnu/`

If this does not solve your problem, please check [FindMbedTLS.cmake](https://github.com/valiot/opex62541/blob/master/src/FindMbedTLS.cmake),  that part of the code, is where the library address is defined, automatically or manually, using environment variables.

I think you could also use `LD_PATH_LIBRARY`, to explicitly indicate the address.

Greetings.

**Comment by simonbowen** [comment]
Hi @alde103 

Thank you for responding. I have all the packages installed. 

My paths look the same as yours. 

![Screenshot 2021-03-05 at 08 32 42](https://user-images.githubusercontent.com/8931/110089025-862eb200-7d8d-11eb-8fa0-d131ed666360.png)

Also my LD_PATH_LIBRARY env variable is empty at the moment. 

I did perform a dist upgrade from 18.04 to 20.20, could this be the issue? Perhaps I need to recompile something somewhere?

I am not knowledgable on C or GCC so please excuse my ignorance when it comes to these things. 

Edit: Error when doing a `mix run`

![Screenshot 2021-03-05 at 09 39 57](https://user-images.githubusercontent.com/8931/110097386-dd855000-7d96-11eb-9978-90e00b96768d.png)

**Comment by alde103** [comment]
try this 
```bash
ls /usr/lib/x86_64-linux-gnu/ | grep 'mbed'
```

**Comment by simonbowen** [comment]
Hi @alde103 

I actually just solved this by running

```
sudo ln -sf /usr/lib/x86_64-linux-gnu/libmbedcrypto.so /usr/lib/x86_64-linux-gnu/libmbedcrypto.so.1
```

Here is the output as requested.

```
simonbowen@ubuntu:~/opcua$ ls /usr/lib/x86_64-linux-gnu/ | grep 'mbed'
libfontembed.so.1
libfontembed.so.1.0.0
libmbedcrypto.a
libmbedcrypto.so
libmbedcrypto.so.1
libmbedcrypto.so.2.16.3
libmbedcrypto.so.3
libmbedtls.a
libmbedtls.so
libmbedtls.so.12
libmbedtls.so.2.16.3
libmbedx509.a
libmbedx509.so
libmbedx509.so.0
libmbedx509.so.2.16.3
```

**Comment by alde103** [comment]
Cool, can I close the issue? @simonbowen

**Comment by simonbowen** [comment]
Sure, I'll open a PR with updated documentation to get it running on Ubuntu 20.20.
